#include "utils.h"

#ifdef M

#define CONCAT2(a,b) a##b
#define CONCAT3(a,b,c) a##b##c
#define EXPAND2(a,b) CONCAT2(a,b)
#define EXPAND3(a,b,c) CONCAT3(a,b,c)

    #define rbc_field_init EXPAND3(rbc_,M,_field_init)
    #define rbc_qre EXPAND3(rbc_,M,_qre)
    #define rbc_qre_init_modulus EXPAND3(rbc_,M,_qre_init_modulus)
    #define rbc_qre_clear_modulus EXPAND3(rbc_,M,_qre_clear_modulus)
    #define rbc_qre_get_modulus EXPAND3(rbc_,M,_qre_get_modulus)
    #define rbc_qre_init EXPAND3(rbc_,M,_qre_init)
    #define rbc_qre_clear EXPAND3(rbc_,M,_qre_clear)
    #define rbc_qre_set_zero EXPAND3(rbc_,M,_qre_set_zero)
    #define rbc_qre_set_random EXPAND3(rbc_,M,_qre_set_random)
    #define rbc_qre_set_random_from_xof EXPAND3(rbc_,M,_qre_set_random_from_xof)
    #define rbc_qre_set_random_full_rank EXPAND3(rbc_,M,_qre_set_random_full_rank)
    #define rbc_qre_set_random_full_rank_with_one EXPAND3(rbc_,M,_qre_set_random_full_rank_with_one)
    #define rbc_qre_set_random_from_support EXPAND3(rbc_,M,_qre_set_random_from_support)
    #define rbc_qre_set_random_pair_from_support EXPAND3(rbc_,M,_qre_set_random_pair_from_support)
    #define rbc_qre_is_equal_to EXPAND3(rbc_,M,_qre_is_equal_to)
    #define rbc_qre_add EXPAND3(rbc_,M,_qre_add)
    #define rbc_qre_mul EXPAND3(rbc_,M,_qre_mul)
    #define rbc_qre_inv EXPAND3(rbc_,M,_qre_inv)
    #define rbc_qre_to_string EXPAND3(rbc_,M,_qre_to_string)
    #define rbc_qre_from_string EXPAND3(rbc_,M,_qre_from_string)
    #define rbc_qre_print EXPAND3(rbc_,M,_qre_print)
    #define rbc_qre_set_monomial EXPAND3(rbc_,M,_qre_set_monomial)
    #define rbc_qre_rot EXPAND3(rbc_,M,_qre_rot)

    #define rbc_vec EXPAND3(rbc_,M,_vec)
    #define rbc_vec_init EXPAND3(rbc_,M,_vec_init)
    #define rbc_vec_clear EXPAND3(rbc_,M,_vec_clear)
    #define rbc_vec_set_zero EXPAND3(rbc_,M,_vec_set_zero)
    #define rbc_vec_set EXPAND3(rbc_,M,_vec_set)
    #define rbc_vec_set_random EXPAND3(rbc_,M,_vec_set_random)
    #define rbc_vec_set_random_tmp EXPAND3(rbc_,M,_vec_set_random_tmp)
    #define rbc_vec_set_random_from_xof EXPAND3(rbc_,M,_vec_set_random_from_xof)
    #define rbc_vec_set_random_fixed_rank EXPAND3(rbc_,M,_vec_set_random_fixed_rank)
    #define rbc_vec_set_random_full_rank EXPAND3(rbc_,M,_vec_set_random_full_rank)
    #define rbc_vec_set_random_full_rank_with_one EXPAND3(rbc_,M,_vec_set_random_full_rank_with_one)
    #define rbc_vec_set_random_full_rank_with_one_tmp EXPAND3(rbc_,M,_vec_set_random_full_rank_with_one_tmp)
    #define rbc_vec_set_random_from_support EXPAND3(rbc_,M,_vec_set_random_from_support)
    #define rbc_vec_set_random_from_support_tmp EXPAND3(rbc_,M,_vec_set_random_from_support_tmp)
    #define rbc_vec_set_random_pair_from_support EXPAND3(rbc_,M,_vec_set_random_pair_from_support)
    #define rbc_vec_gauss EXPAND3(rbc_,M,_vec_gauss)
    #define rbc_vec_get_rank EXPAND3(rbc_,M,_vec_get_rank)
    #define rbc_vec_echelonize EXPAND3(rbc_,M,_vec_echelonize)
    #define rbc_vec_add EXPAND3(rbc_,M,_vec_add)
    #define rbc_vec_inner_product EXPAND3(rbc_,M,_vec_inner_product)
    #define rbc_vec_scalar_mul EXPAND3(rbc_,M,_vec_scalar_mul)
    #define rbc_vec_to_string EXPAND3(rbc_,M,_vec_to_string)
    #define rbc_vec_from_string EXPAND3(rbc_,M,_vec_from_string)
    #define rbc_vec_from_bytes EXPAND3(rbc_,M,_vec_from_bytes)
    #define rbc_vec_from_bytes_without_mask EXPAND3(rbc_,M,_vec_from_bytes_without_mask)
    #define rbc_vec_to_bytes EXPAND3(rbc_,M,_vec_to_bytes)
    #define rbc_vec_print EXPAND3(rbc_,M,_vec_print)

    #define rbc_vspace EXPAND3(rbc_,M,_vspace)
    #define rbc_vspace_init EXPAND3(rbc_,M,_vspace_init)
    #define rbc_vspace_clear EXPAND3(rbc_,M,_vspace_clear)
    #define rbc_vspace_set EXPAND3(rbc_,M,_vspace_set)
    #define rbc_vspace_set_zero EXPAND3(rbc_,M,_vspace_set_zero)
    #define rbc_vspace_set_random_full_rank EXPAND3(rbc_,M,_vspace_set_random_full_rank)
    #define rbc_vspace_set_random_full_rank_with_one EXPAND3(rbc_,M,_vspace_set_random_full_rank_with_one)
    #define rbc_vspace_set_random_full_rank_with_one_tmp EXPAND3(rbc_,M,_vspace_set_random_full_rank_with_one_tmp)
    #define rbc_vspace_direct_sum EXPAND3(rbc_,M,_vspace_direct_sum)
    #define rbc_vspace_intersection EXPAND3(rbc_,M,_vspace_intersection)
    #define rbc_vspace_product EXPAND3(rbc_,M,_vspace_product)
    #define rbc_vspace_print EXPAND3(rbc_,M,_vspace_print)

    #define rbc_lrpc_RSR EXPAND3(rbc_,M,_lrpc_RSR)

#endif